<li data-type="between">
    <h5>Between <a href="#" class="delete-v">(Delete)</a></h5>
    <div class="form-group">
        <label>Min</label>
        <input name="min" type="text" class="form-control" value="">                    
    </div>
    <div class="form-group">
        <label>Max</label>
        <input name="max" type="text" class="form-control" value="">                    
    </div>
</li>