<?if( ( isset($field) && $field['character_maximum_length'] > 0  ) || isset($isTemplate) ):?>

<li data-type="string-length">
    <h5>String Length <a href="#" class="delete-v">(Delete)</a></h5>
    <div class="form-group">
        <label>Min</label>
        <input name="min" type="text" class="form-control" value="0">                    
    </div>
    <div class="form-group">
        <label>Max</label>
        <input name="max" type="text" class="form-control" value="<?=$field['character_maximum_length']?>">                    
    </div>
</li>
<?endif;?>